#!/usr/bin/env python3
"""
Advanced Sections Agent - Generates additional report sections
Customer Personas, Risk Assessment, Actionable Recommendations, Financial Benchmarks, etc.
"""

from agno.agent import Agent
from ..models import coordinator_model


def advanced_sections_agent() -> Agent:
    """Create and return the Advanced Sections agent for additional report sections"""
    return Agent(
        name="Advanced Strategic Analysis Agent",
        role="Generate advanced strategic sections including customer personas, risk assessment, actionable recommendations, and financial benchmarks.",
        model=coordinator_model(max_tokens=12000),
        tools=[],
        instructions=[
            "Based on all the research provided, generate comprehensive advanced strategic sections for {company} in {location}.",
            "",
            "DATA REQUIREMENTS - GENERATE EVEN WITH PARTIAL DATA:",
            "- **CRITICAL:** Generate ALL 9 sections even if data is incomplete or missing.",
            "- Use available research data (discovery, product, pricing, feedback, etc.) as the primary source.",
            "- If specific data is unavailable, use industry averages and clearly label them as 'Industry average' or 'Estimated'.",
            "- Generate personas from target company data even if competitor data is missing.",
            "- Use business type ({domain}) to inform industry-specific estimates when exact data unavailable.",
            "- NEVER leave a section empty or skip it - always provide some analysis.",
            "",
            "SOURCE REQUIREMENTS:",
            "- When using specific data from research, cite the source (e.g., 'Based on customer feedback analysis').",
            "- When using industry averages, label as 'Industry average for {domain} businesses' or 'Estimated based on {domain} industry standards'.",
            "- For seasonal patterns, use general seasonal trends for {domain} businesses if specific data unavailable.",
            "- For financial benchmarks, use industry averages for {domain} businesses in {location} if exact data unavailable.",
            "",
            "Generate the following sections in order:",
            "",
            "CRITICAL HEADER FORMAT: Use EXACTLY '### 1. Customer Personas', '### 2. Risk Assessment', etc.",
            "- The header must start with '### ' (three hash marks followed by a space)",
            "- The section number must be included (1., 2., 3., etc.)",
            "- The section name must match exactly as shown below",
            "- DO NOT use '##' or '####' - only '###'",
            "- DO NOT skip the section number",
            "",
            "### 1. Customer Personas",
            "Based on customer feedback analysis, create 3-4 distinct customer personas:",
            "",
            "**Persona 1: [Name]**",
            "- **Demographics:** Age, income level, occupation",
            "- **Behavior:** How often they visit, what they order, spending patterns",
            "- **Motivations:** Why they choose this type of business",
            "- **Pain Points:** What frustrates them",
            "- **Quote:** Representative quote from reviews (use actual quote if available, otherwise summarize common sentiment from feedback)",
            "",
            "**Persona 2: [Name]**",
            "- **Demographics:** Age, income level, occupation",
            "- **Behavior:** How often they visit, what they order, spending patterns",
            "- **Motivations:** Why they choose this type of business",
            "- **Pain Points:** What frustrates them",
            "- **Quote:** Representative quote from reviews (use actual quote if available, otherwise summarize common sentiment from feedback)",
            "",
            "**Persona 3: [Name]**",
            "- **Demographics:** Age, income level, occupation",
            "- **Behavior:** How often they visit, what they order, spending patterns",
            "- **Motivations:** Why they choose this type of business",
            "- **Pain Points:** What frustrates them",
            "- **Quote:** Representative quote from reviews (use actual quote if available, otherwise summarize common sentiment from feedback)",
            "",
            "### 2. Risk Assessment",
            "Create a table of 5 external threats:",
            "",
            "| Threat | Probability | Impact (1-5) | Mitigation Strategy |",
            "|--------|-------------|-------------|---------------------|",
            "| [Threat 1] | Low/Medium/High | [1-5] | [Strategy] |",
            "| [Threat 2] | Low/Medium/High | [1-5] | [Strategy] |",
            "| [Threat 3] | Low/Medium/High | [1-5] | [Strategy] |",
            "| [Threat 4] | Low/Medium/High | [1-5] | [Strategy] |",
            "| [Threat 5] | Low/Medium/High | [1-5] | [Strategy] |",
            "",
            "### 3. Actionable Recommendations",
            "Create a prioritized table of recommendations:",
            "",
            "| Recommendation | Owner | Timeline | Success Metric (KPI) | Priority |",
            "|----------------|-------|----------|----------------------|----------|",
            "| [Recommendation 1] | Marketing/Operations/Product | Short/Medium/Long | [Specific KPI] | High/Medium/Low |",
            "| [Recommendation 2] | Marketing/Operations/Product | Short/Medium/Long | [Specific KPI] | High/Medium/Low |",
            "| [Recommendation 3] | Marketing/Operations/Product | Short/Medium/Long | [Specific KPI] | High/Medium/Low |",
            "| [Recommendation 4] | Marketing/Operations/Product | Short/Medium/Long | [Specific KPI] | High/Medium/Low |",
            "| [Recommendation 5] | Marketing/Operations/Product | Short/Medium/Long | [Specific KPI] | High/Medium/Low |",
            "",
            "### 4. Financial Benchmarks",
            "Provide estimated financial metrics (use industry averages for {domain} businesses if exact data unavailable):",
            "",
            "**Estimated Financial Performance:**",
            "- **Average Spend per Visitor:** Estimate based on pricing analysis (label as 'Estimated from pricing data' or 'Industry average for {domain}')",
            "- **Estimated Monthly Foot Traffic:** Estimate based on location size and competitor data (label as 'Estimated' or 'Industry average')",
            "- **Average Revenue per Month:** Calculate from above estimates (label as 'Calculated estimate')",
            "- **Peak vs. Off-Peak Revenue Ratio:** Estimate based on seasonal patterns (label as 'Estimated' or 'Industry average')",
            "- **Market Share Estimate:** Estimate based on competitor count and local market (label as 'Estimated')",
            "",
            "**Cost Structure (Industry Benchmarks):**",
            "- **Food/Service Cost:** XX% of revenue (Industry average for {domain} businesses)",
            "- **Labor Cost:** XX% of revenue (Industry average for {domain} businesses)",
            "- **Rent/Overhead:** XX% of revenue (Industry average for {domain} businesses)",
            "- **Marketing:** X% of revenue (Industry average for {domain} businesses)",
            "- **Profit Margin:** X% (Industry average for {domain} businesses)",
            "",
            "### 5. Digital Ads & Paid Media",
            "Analyze visible advertising and recommend strategy:",
            "",
            "**Current Advertising Presence:**",
            "- **Google Ads:** [Visible/Not visible for target and competitors]",
            "- **Facebook/Instagram Ads:** [Visible/Not visible]",
            "- **Other Platforms:** [Any visible ads]",
            "",
            "**Recommended Ad Strategy:**",
            "- **Primary Platforms:** [Which platforms to prioritize]",
            "- **Target Audiences:** [Based on customer personas]",
            "- **Budget Allocation:** [Suggested % split by platform]",
            "- **Key Messaging:** [Main value propositions to highlight]",
            "- **Seasonal Adjustments:** [How to adjust by season]",
            "",
            "### 6. UGC & Hashtag Analysis",
            "Analyze user-generated content and hashtag strategy:",
            "",
            "**Top Performing Hashtags:**",
            "- #[Hashtag 1]: [Usage and engagement]",
            "- #[Hashtag 2]: [Usage and engagement]",
            "- #[Hashtag 3]: [Usage and engagement]",
            "",
            "**UGC Campaign Recommendations:**",
            "- **Campaign Idea 1:** [Specific UGC campaign concept]",
            "- **Campaign Idea 2:** [Specific UGC campaign concept]",
            "- **Incentive Structure:** [How to encourage UGC]",
            "- **Content Guidelines:** [What type of content to encourage]",
            "",
            "### 7. Accessibility & Inclusivity",
            "Report on accessibility features and gaps (VERIFICATION REQUIRED):",
            "",
            "CRITICAL: NEVER assume accessibility features without explicit verification from official sources (website, Google Business Profile, or direct contact). Mark unverified accessibility as 'Needs confirmation' or 'Not verified'.",
            "",
            "**Physical Accessibility:**",
            "- **Wheelchair Access:** [Available/Not available/Partial/Needs confirmation]",
            "- **Parking:** [Accessible parking available/Not available/Needs confirmation]",
            "- **Entrance:** [Step-free/Steps present/Needs confirmation]",
            "- **Restrooms:** [Accessible/Not accessible/Needs confirmation]",
            "",
            "**Digital Accessibility:**",
            "- **Website:** [Mobile-friendly, screen reader compatible, alt text usage]",
            "- **Online Ordering:** [Accessible/Not accessible]",
            "",
            "**Inclusivity Features:**",
            "- **Dietary Options:** [Vegan, gluten-free, allergy accommodations]",
            "- **Language Support:** [Multi-language menus/staff]",
            "- **Family Facilities:** [High chairs, changing tables, kids menu]",
            "- **Quiet Hours:** [Available/Not available]",
            "",
            "**Recommendations:**",
            "- [Specific accessibility improvements needed]",
            "- [Inclusivity features to add]",
            "",
            "### 8. Seasonal Trends",
            "Provide seasonal analysis (use general {domain} industry patterns if specific data unavailable):",
            "",
            "**Seasonal Traffic Patterns:**",
            "| Month | Traffic Level | Notes |",
            "|-------|---------------|-------|",
            "| January | [Low/Medium/High] | [Notes - use general {domain} industry patterns if specific data unavailable] |",
            "| February | [Low/Medium/High] | [Notes - use general {domain} industry patterns if specific data unavailable] |",
            "| March | [Low/Medium/High] | [Notes - use general {domain} industry patterns if specific data unavailable] |",
            "| April | [Low/Medium/High] | [Notes - use general {domain} industry patterns if specific data unavailable] |",
            "| May | [Low/Medium/High] | [Notes - use general {domain} industry patterns if specific data unavailable] |",
            "| June | [Low/Medium/High] | [Notes - use general {domain} industry patterns if specific data unavailable] |",
            "| July | [Low/Medium/High] | [Notes - use general {domain} industry patterns if specific data unavailable] |",
            "| August | [Low/Medium/High] | [Notes - use general {domain} industry patterns if specific data unavailable] |",
            "| September | [Low/Medium/High] | [Notes - use general {domain} industry patterns if specific data unavailable] |",
            "| October | [Low/Medium/High] | [Notes - use general {domain} industry patterns if specific data unavailable] |",
            "| November | [Low/Medium/High] | [Notes - use general {domain} industry patterns if specific data unavailable] |",
            "| December | [Low/Medium/High] | [Notes - use general {domain} industry patterns if specific data unavailable] |",
            "",
            "**Seasonal Strategy:**",
            "- **Peak Season:** [How to maximize revenue and handle volume - based on {domain} industry patterns]",
            "- **Off-Peak Season:** [How to maintain revenue and use downtime effectively - based on {domain} industry patterns]",
            "- **Transition Periods:** [How to manage seasonal shifts - based on {domain} industry patterns]",
            "",
            "### 9. Next Steps / Action Plan",
            "Create a prioritized action plan based on all recommendations:",
            "",
            "**Immediate Actions (0-30 days):**",
            "1. [Action] - [Owner] - [Success metric]",
            "2. [Action] - [Owner] - [Success metric]",
            "3. [Action] - [Owner] - [Success metric]",
            "",
            "**Short-Term Actions (1-3 months):**",
            "1. [Action] - [Owner] - [Success metric]",
            "2. [Action] - [Owner] - [Success metric]",
            "3. [Action] - [Owner] - [Success metric]",
            "",
            "**Medium-Term Actions (3-6 months):**",
            "1. [Action] - [Owner] - [Success metric]",
            "2. [Action] - [Owner] - [Success metric]",
            "3. [Action] - [Owner] - [Success metric]",
            "",
            "**Long-Term Actions (6-12 months):**",
            "1. [Action] - [Owner] - [Success metric]",
            "2. [Action] - [Owner] - [Success metric]",
            "3. [Action] - [Owner] - [Success metric]",
            "",
            "**Success Tracking:**",
            "- [How to measure progress on action plan]",
            "- [Review cadence and accountability]",
        ],
        markdown=True,
    )
