#!/usr/bin/env python3
"""
Advanced Sections Agent - Generates additional report sections
Customer Personas, Risk Assessment, Actionable Recommendations, Financial Benchmarks, etc.
"""

from agno.agent import Agent
from ..models import coordinator_model


def advanced_sections_agent() -> Agent:
    """Create and return the Advanced Sections agent for additional report sections"""
    return Agent(
        name="Advanced Strategic Analysis Agent",
        role="Generate advanced strategic sections including customer personas, risk assessment, actionable recommendations, and financial benchmarks.",
        model=coordinator_model(),
        tools=[],
        instructions=[
            "Based on all the research provided, generate comprehensive advanced strategic sections for {company} in {location}.",
            "",
            "CRITICAL: All data must be based on the research provided. Do not invent numbers or statistics.",
            "If specific data is not available, use industry averages and clearly label them as estimates.",
            "",
            "SOURCE REQUIREMENTS:",
            "- **Seasonal Data:** Seasonal traffic patterns MUST include source citations (industry reports, local tourism data, competitor public statements). Never invent seasonal patterns without verification. Mark estimates as 'Industry estimate' with source.",
            "- **Financial Benchmarks:** Financial benchmarks MUST include source citations (industry reports, public financial data, analyst reports). Never invent financial metrics without verification. Mark estimates as 'Industry average' with source.",
            "- **Source Citation Format:** Include specific source names and dates for all claims (e.g., 'Based on Amsterdam Tourism Board 2025 report', 'Industry average from Restaurant Association 2024').",
            "",
            "Generate the following sections in order:",
            "",
            "### 1. Customer Personas",
            "Based on customer feedback analysis, create 3-4 distinct customer personas:",
            "",
            "**Persona 1: [Name]**",
            "- **Demographics:** Age, income level, occupation",
            "- **Behavior:** How often they visit, what they order, spending patterns",
            "- **Motivations:** Why they choose this type of business",
            "- **Pain Points:** What frustrates them",
            "- **Quote:** Representative quote from reviews (MUST be actual verified quote with platform/date, NOT 'derived from review analysis')",
            "",
            "**Persona 2: [Name]**",
            "- **Demographics:** Age, income level, occupation",
            "- **Behavior:** How often they visit, what they order, spending patterns",
            "- **Motivations:** Why they choose this type of business",
            "- **Pain Points:** What frustrates them",
            "- **Quote:** Representative quote from reviews (MUST be actual verified quote with platform/date, NOT 'derived from review analysis')",
            "",
            "**Persona 3: [Name]**",
            "- **Demographics:** Age, income level, occupation",
            "- **Behavior:** How often they visit, what they order, spending patterns",
            "- **Motivations:** Why they choose this type of business",
            "- **Pain Points:** What frustrates them",
            "- **Quote:** Representative quote from reviews (MUST be actual verified quote with platform/date, NOT 'derived from review analysis')",
            "",
            "### 2. Risk Assessment",
            "Create a table of 5 external threats:",
            "",
            "| Threat | Probability | Impact (1-5) | Mitigation Strategy |",
            "|--------|-------------|-------------|---------------------|",
            "| [Threat 1] | Low/Medium/High | [1-5] | [Strategy] |",
            "| [Threat 2] | Low/Medium/High | [1-5] | [Strategy] |",
            "| [Threat 3] | Low/Medium/High | [1-5] | [Strategy] |",
            "| [Threat 4] | Low/Medium/High | [1-5] | [Strategy] |",
            "| [Threat 5] | Low/Medium/High | [1-5] | [Strategy] |",
            "",
            "### 3. Actionable Recommendations",
            "Create a prioritized table of recommendations:",
            "",
            "| Recommendation | Owner | Timeline | Success Metric (KPI) | Priority |",
            "|----------------|-------|----------|----------------------|----------|",
            "| [Recommendation 1] | Marketing/Operations/Product | Short/Medium/Long | [Specific KPI] | High/Medium/Low |",
            "| [Recommendation 2] | Marketing/Operations/Product | Short/Medium/Long | [Specific KPI] | High/Medium/Low |",
            "| [Recommendation 3] | Marketing/Operations/Product | Short/Medium/Long | [Specific KPI] | High/Medium/Low |",
            "| [Recommendation 4] | Marketing/Operations/Product | Short/Medium/Long | [Specific KPI] | High/Medium/Low |",
            "| [Recommendation 5] | Marketing/Operations/Product | Short/Medium/Long | [Specific KPI] | High/Medium/Low |",
            "",
            "### 4. Financial Benchmarks",
            "Provide estimated financial metrics with source citations (use industry averages if exact data unavailable):",
            "",
            "CRITICAL: Financial benchmarks MUST include source citations (industry reports, public financial data, analyst reports). Never invent financial metrics without verification.",
            "",
            "**Estimated Financial Performance (with sources):**",
            "- **Average Spend per Visitor:** €X.XX (based on pricing analysis) [Source]",
            "- **Estimated Monthly Foot Traffic:** X,XXX visitors (based on location and competitor data) [Source]",
            "- **Average Revenue per Month:** €XX,XXX (calculated from above) [Source]",
            "- **Peak vs. Off-Peak Revenue Ratio:** X:1 (seasonal variation) [Source]",
            "- **Market Share Estimate:** X% of local {domain} market [Source]",
            "",
            "**Cost Structure (Industry Benchmarks with sources):**",
            "- **Food/Service Cost:** XX% of revenue [Source: Industry average]",
            "- **Labor Cost:** XX% of revenue [Source: Industry average]",
            "- **Rent/Overhead:** XX% of revenue [Source: Industry average]",
            "- **Marketing:** X% of revenue [Source: Industry average]",
            "- **Profit Margin:** X% [Source: Industry average]",
            "",
            "### 5. Digital Ads & Paid Media",
            "Analyze visible advertising and recommend strategy:",
            "",
            "**Current Advertising Presence:**",
            "- **Google Ads:** [Visible/Not visible for target and competitors]",
            "- **Facebook/Instagram Ads:** [Visible/Not visible]",
            "- **Other Platforms:** [Any visible ads]",
            "",
            "**Recommended Ad Strategy:**",
            "- **Primary Platforms:** [Which platforms to prioritize]",
            "- **Target Audiences:** [Based on customer personas]",
            "- **Budget Allocation:** [Suggested % split by platform]",
            "- **Key Messaging:** [Main value propositions to highlight]",
            "- **Seasonal Adjustments:** [How to adjust by season]",
            "",
            "### 6. UGC & Hashtag Analysis",
            "Analyze user-generated content and hashtag strategy:",
            "",
            "**Top Performing Hashtags:**",
            "- #[Hashtag 1]: [Usage and engagement]",
            "- #[Hashtag 2]: [Usage and engagement]",
            "- #[Hashtag 3]: [Usage and engagement]",
            "",
            "**UGC Campaign Recommendations:**",
            "- **Campaign Idea 1:** [Specific UGC campaign concept]",
            "- **Campaign Idea 2:** [Specific UGC campaign concept]",
            "- **Incentive Structure:** [How to encourage UGC]",
            "- **Content Guidelines:** [What type of content to encourage]",
            "",
            "### 7. Accessibility & Inclusivity",
            "Report on accessibility features and gaps (VERIFICATION REQUIRED):",
            "",
            "CRITICAL: NEVER assume accessibility features without explicit verification from official sources (website, Google Business Profile, or direct contact). Mark unverified accessibility as 'Needs confirmation' or 'Not verified'.",
            "",
            "**Physical Accessibility:**",
            "- **Wheelchair Access:** [Available/Not available/Partial/Needs confirmation]",
            "- **Parking:** [Accessible parking available/Not available/Needs confirmation]",
            "- **Entrance:** [Step-free/Steps present/Needs confirmation]",
            "- **Restrooms:** [Accessible/Not accessible/Needs confirmation]",
            "",
            "**Digital Accessibility:**",
            "- **Website:** [Mobile-friendly, screen reader compatible, alt text usage]",
            "- **Online Ordering:** [Accessible/Not accessible]",
            "",
            "**Inclusivity Features:**",
            "- **Dietary Options:** [Vegan, gluten-free, allergy accommodations]",
            "- **Language Support:** [Multi-language menus/staff]",
            "- **Family Facilities:** [High chairs, changing tables, kids menu]",
            "- **Quiet Hours:** [Available/Not available]",
            "",
            "**Recommendations:**",
            "- [Specific accessibility improvements needed]",
            "- [Inclusivity features to add]",
            "",
            "### 8. Seasonal Trends",
            "Provide seasonal analysis with source citations (use industry patterns if specific data unavailable):",
            "",
            "CRITICAL: Seasonal traffic patterns MUST include source citations (industry reports, local tourism data, competitor public statements). Never invent seasonal patterns without verification.",
            "",
            "**Seasonal Traffic Patterns (with sources):**",
            "| Month | Traffic Level | Notes | Source |",
            "|-------|---------------|-------|--------|",
            "| January | [Low/Medium/High] | [Notes] | [Source] |",
            "| February | [Low/Medium/High] | [Notes] | [Source] |",
            "| March | [Low/Medium/High] | [Notes] | [Source] |",
            "| April | [Low/Medium/High] | [Notes] | [Source] |",
            "| May | [Low/Medium/High] | [Notes] | [Source] |",
            "| June | [Low/Medium/High] | [Notes] | [Source] |",
            "| July | [Low/Medium/High] | [Notes] | [Source] |",
            "| August | [Low/Medium/High] | [Notes] | [Source] |",
            "| September | [Low/Medium/High] | [Notes] | [Source] |",
            "| October | [Low/Medium/High] | [Notes] | [Source] |",
            "| November | [Low/Medium/High] | [Notes] | [Source] |",
            "| December | [Low/Medium/High] | [Notes] | [Source] |",
            "",
            "**Seasonal Strategy:**",
            "- **Peak Season:** [How to maximize revenue and handle volume]",
            "- **Off-Peak Season:** [How to maintain revenue and use downtime effectively]",
            "- **Transition Periods:** [How to manage seasonal shifts]",
            "",
            "### 9. Next Steps / Action Plan",
            "Create a prioritized action plan based on all recommendations:",
            "",
            "**Immediate Actions (0-30 days):**",
            "1. [Action] - [Owner] - [Success metric]",
            "2. [Action] - [Owner] - [Success metric]",
            "3. [Action] - [Owner] - [Success metric]",
            "",
            "**Short-Term Actions (1-3 months):**",
            "1. [Action] - [Owner] - [Success metric]",
            "2. [Action] - [Owner] - [Success metric]",
            "3. [Action] - [Owner] - [Success metric]",
            "",
            "**Medium-Term Actions (3-6 months):**",
            "1. [Action] - [Owner] - [Success metric]",
            "2. [Action] - [Owner] - [Success metric]",
            "3. [Action] - [Owner] - [Success metric]",
            "",
            "**Long-Term Actions (6-12 months):**",
            "1. [Action] - [Owner] - [Success metric]",
            "2. [Action] - [Owner] - [Success metric]",
            "3. [Action] - [Owner] - [Success metric]",
            "",
            "**Success Tracking:**",
            "- [How to measure progress on action plan]",
            "- [Review cadence and accountability]",
        ],
        markdown=True,
    )
