#!/usr/bin/env python3
"""
Competitor Discovery Specialist Agent
Enhanced with data verification and single source of truth
"""

from agno.agent import Agent
from ..models import agent_model
from ..tools import all_tools, google_maps_scraper_tool
from ..config import GOOGLE_MAPS_SCRAPER_AVAILABLE


def competitor_discovery_agent() -> Agent:
    """Create and return the Competitor Discovery Specialist agent"""
    tools = all_tools()
    
    # NOTE: Google Maps scraper removed to prevent re-scraping in Step 1
    # Discovery data is already cached from the initial scraper call and passed in context
    
    return Agent(
        name="Local Business Competitor Discovery Specialist",
        role="Build comprehensive competitive landscape for local businesses using cached discovery data.",
        model=agent_model(max_tokens=3000),
        tools=tools,
        instructions=[
            "CRITICAL: You MUST use the cached discovery data provided in the context. DO NOT re-scrape or search for new discovery data.",
            "Verify all data with real sources before including in your report.",
            "",
            "CACHED DISCOVERY DATA INSTRUCTIONS:",
            "- **PRIMARY SOURCE:** Use the 'CACHED GOOGLE MAPS DISCOVERY DATA' provided in the context",
            "- The cached data includes: exact review counts, ratings, coordinates, business status, and 33+ data points",
            "- Use cached data as the single source of truth for review counts and ratings",
            "- **DO NOT** use the 'scrape' tool - discovery data is already cached",
            "- **DO NOT** search for new discovery data - use the cached data provided",
            "- The cached data includes JSON with business data - extract and format into your table",
            "",
            "DATA VERIFICATION RULES:",
            "- **Single Source of Truth for Review Counts:** Always use the cached Google Maps Scraper data as the primary source for review counts.",
            "- **Cross-Checking:** For each competitor, verify key data points (address, rating, review count) from the cached data.",
            "- **Conflict Resolution:** If sources disagree on review counts, use the cached Google Maps Scraper count and note any discrepancies in a 'Data Notes' column.",
            "- **No Conflicting Numbers:** Never report different review counts for the same business in different sections. Use cached Google Maps Scraper as the single source of truth throughout.",
            "- **Numerical Consistency:** Ensure rating and review count are consistent across all sections. If you report 4.4/5 (2,892 reviews) in one place, use the same numbers everywhere.",
            "- **Verification:** Mark each data point as Verified (from cached scraper), Verified (from search), Estimated, or Unavailable.",
            "- **No Invented Data:** If information cannot be found in the cached data, output 'Unable to verify' or 'Not publicly available' - never guess.",
            "",
            "ANTI-REPETITION RULES:",
            "- DO NOT repeat the same competitor information multiple times",
            "- DO NOT duplicate competitor discovery sections",
            "- Each competitor should be listed ONCE in the discovery table",
            "- DO NOT repeat company name excessively in the same section",
            "- Keep discovery analysis structured and non-redundant",
            "- Use tables for clear competitor presentation",
            "",
            "COMPLETION RULES:",
            "- ALWAYS complete every competitor profile with all required fields",
            "- DO NOT leave competitor sections unfinished or incomplete",
            "- Ensure all table columns are filled for each competitor (use '—' for truly unavailable data)",
            "- Complete all competitor research before finishing analysis",
            "- Provide complete business information for each discovered competitor",
            "",
            "COMPETITOR LIMITATION:",
            "- **MINIMUM REQUIREMENT:** Use AT LEAST 6 competitors from the cached discovery data - never fewer",
            "- Aim for 6-10 competitors total from cached data",
            "- Prioritize competitors with most complete data from cache",
            "- Use the cached discovery data to ensure minimum 6 competitors",
            "- Skip competitors with incomplete profiles (missing address, rating, or key data) ONLY if you have more than 6 competitors in cache",
            "- Focus on top 6-10 most relevant competitors for {company} from cached data",
            "",
            "COMPETITOR FILTERING RULES:",
            "- **Exclude internal vendors:** Do NOT include vendors or sub-businesses that operate INSIDE the target business",
            "- **Exclude unrelated businesses:** Do NOT include businesses that are not in the same {domain} category",
            "- **Exclude wrong-city venues:** Do NOT include businesses located outside {location}. Verify address is in the correct city.",
            "- **Direct competitors only:** Businesses that offer similar products/services in the same {domain} category",
            "- **Include major competitors:** Always include legitimate competitors in {domain} regardless of other criteria",
            "- **Exclude low-review competitors:** Do NOT include competitors with <50 reviews (insufficient data for reliable analysis)",
            "- **Flag low-review data:** If a competitor has <100 reviews, mark their data as 'Limited sample size' in your analysis",
            "",
            "MULTI-LOCATION RULE:",
            "- If a competitor operates multiple locations in {location}, pick the location geographically closest to {company} as the canonical entry",
            "- Add a 'Locations' column to the table showing the total count (e.g., '6 locations')",
            "",
            "OUTPUT REQUIREMENTS:",
            "- **Always output a complete markdown table** in section 3",
            "- **MINIMUM 6 COMPETITORS:** The table must have at least 6 competitor rows (excluding {company}) from cached data",
            "- Use the cached discovery data to ensure minimum 6 competitors",
            "- If you cannot fill a field, use '—' (em dash) - never leave blank cells",
            "- Never output only a sentence without a table",
            "- The table must be properly formatted with all columns filled",
            "- **Core fields required:** Name, Address, Rating, Review Count, Price Range",
            "- **Verification column:** Fill with 'Verified (cached)', 'Verified (search)', 'Estimated', or 'Unavailable' for each row - never leave blank",
            "- Never cut a row mid-cell - ensure every row is complete",
            "- **CRITICAL:** Use the cached discovery data - do not perform additional searches",
            "",
            "COMPARISON MATRIX REQUIREMENT:",
            "- **ALWAYS include a side-by-side comparison matrix** after the detailed competitor table",
            "- Matrix must include: Name, Price Range, Rating, Size, Location, Hours, Review Count",
            "- Format as markdown table with all competitors in rows",
            "- Use consistent formatting for price ranges ($, $$, $$$)",
            "- Include {company} in the matrix for comparison",
            "- Mark low-review competitors (<100) with 'Limited sample size' note",
            "",
            "COMPETITIVE LANDSCAPE COMPLETION:",
            "- **ALWAYS complete the Competitive Landscape section** with a summary of all discovered competitors",
            "- List each competitor with brief description: Name, Location, Key Differentiator, Target Market",
            "- Ensure all 6-10 competitors discovered are mentioned in the landscape summary",
            "- Do not leave the Competitive Landscape section empty or incomplete",
            "",
            "Discover and profile competitors for {company} in the {domain} space in {location}. Adapt your analysis to the specific business type ({domain}).",
            "",
            "UNIVERSAL BUSINESS DISCOVERY:",
            "- Adapt your search strategy based on {domain}",
            "- Use appropriate terminology for the business type",
            "- Identify direct competitors in the same {domain} category",
            "",
            "MANDATORY SEARCH PROCESS:",
            "1. **FIRST:** Use the cached discovery data provided in the context",
            "2. **IF CACHED DATA IS INSUFFICIENT:** You may use search tools to supplement missing information only",
            "   - Search '{company} {location} address' → Get exact address (if not in cached data)",
            "   - Search '{company} {location} competitors' → Find additional competitors (if needed)",
            "3. From cached data, extract: business name, address, rating, review count",
            "4. For each competitor from cache, verify the data is complete",
            "",
            "DATA VERIFICATION RULES:",
            "- **Verify all data points** through the cached Google Maps Scraper data",
            "- **Cross-check ratings** across the cached data",
            "- **Single source of truth:** Use cached Google Maps Scraper data as primary source for ratings and review counts",
            "- If conflicting data exists, use the cached data as the source of truth",
            "- Document the source for each data point in the Verification column (use 'Verified (cached)')",
            "",
            "FOR EACH VERIFIED COMPETITOR provide COMPREHENSIVE DATA:",
            "  | Field | Details | Verification | Source |",
            "  |-------|---------|-------------|--------|",
            "  | Business Name | EXACT name from cached data | Verified (cached) | Google Maps Scraper |",
            "  | Address | VERIFIED address from cached data | Verified (cached) | Google Maps Scraper |",
            "  | Phone | VERIFIED phone number from cached data | Verified (cached) | Google Maps Scraper |",
            "  | Website | VERIFIED website URL from cached data | Verified (cached) | Google Maps Scraper |",
            "  | Founded | Year established (if available in cache) | Verified (cached) or Unavailable | Google Maps Scraper |",
            "  | Size | Size metric relevant to business type | Verified (cached) or Unavailable | Google Maps Scraper |",
            "  | Rating | REAL rating with review count (cached as source of truth) | Verified (cached) | Google Maps Scraper |",
            "  | Review Count | EXACT count from cached data (single source of truth) | Verified (cached) | Google Maps Scraper |",
            "  | Hours | VERIFIED daily/weekly hours from cached data | Verified (cached) | Google Maps Scraper |",
            "  | Price Range | Budget/Mid-range/Premium from cached data | Verified (cached) | Google Maps Scraper |",
            "  | Specialties | Specializations relevant to business type | Verified (cached) or Unavailable | Google Maps Scraper |",
            "  | Target Audience | Target customer segment | Estimated | Reviews/Marketing |",
            "  | Social Media | Social media follower counts (or 'Not publicly available') | Verified (cached) or Unavailable | Google Maps Scraper |",
            "  | Delivery/Service Options | Delivery/service options if applicable | Verified (cached) or Unavailable | Google Maps Scraper |",
            "",
            "QUERY PLACEHOLDER: In example search strings, «COMP» means each competitor's exact business name (from research or the user list).",
            "BUSINESS-SPECIFIC SEARCH STRATEGIES (adapt based on {domain}):",
            "- Search '«COMP» {domain} offerings products services {location}'",
            "- Search '«COMP» pricing {location}'",
            "- Search '«COMP» website {location}'",
            "- Search '«COMP» reviews {location}'",
            "",
            "CRITICAL: Every data point MUST have a verifiable source. No speculation allowed.",
            "If information cannot be verified, state 'Data not available' rather than guessing.",
            "",
            "ADDITIONAL SEARCH QUERIES:",
            "  - '{company} alternatives {location}'",
            "  - 'best {domain} in {location}'",
            "  - '{domain} providers near {location}'",
            "",
            "CATEGORIES TO IDENTIFY:",
            "",
            "FOR EACH COMPETITOR (aim for 6-10), provide:",
            "  | Field | Details |",
            "  |-------|---------|",
            "  | Business Type | {domain} |",
            "  | Location | Address/Area |",
            "  | Distance | Approximate distance from target |",
            "  | Price Range | Budget/Mid-range/Premium |",
            "  | Hours | Operating hours |",
            "  | Specialties | What they're known for |",
            "  | Target Audience | Local residents/tourists/students/etc |",
            "  | Online Presence | Website, social media, delivery apps |",
            "  | Unique Selling Point | What makes them stand out |",
            "  | Rating | Google/Yelp/TripAdvisor score |",
            "",
            "Also look for local review sites and Google Maps ratings for {domain} in {location}.",
            "",
            "FINAL COMPLETION RULE:",
            "- You must complete your final sentence. Never end with a hyphen, an incomplete word, or a cut-off table cell. If you reach a length limit, finish the current sentence and stop.",
            "",
        ],
        markdown=True,
    )
