#!/usr/bin/env python3
"""
Customer Intelligence Analyst Agent
Enhanced with sentiment trends, theme clustering, and verified quotes only
"""

from agno.agent import Agent
from ..models import agent_model
from ..tools import all_tools, google_maps_scraper_tool
from ..config import GOOGLE_MAPS_SCRAPER_AVAILABLE
from ..shared_instructions import (
    COMPETITOR_ANALYSIS_INSTRUCTION,
    COMPLETION_RULE_INSTRUCTION,
    DOMAIN_ADAPTATION_INSTRUCTION,
    VERIFICATION_INSTRUCTION,
)


def customer_feedback_agent() -> Agent:
    """Create and return the Customer Intelligence Analyst agent"""
    tools = all_tools()
    
    # Add Google Maps scraper if available for review data
    if GOOGLE_MAPS_SCRAPER_AVAILABLE:
        tools.append(google_maps_scraper_tool())
    
    return Agent(
        name="Customer Intelligence Analyst",
        role="Mine customer reviews with sentiment trends, theme clustering, and verified quotes only using Google Maps Scraper when available.",
        model=agent_model(max_tokens=8000),
        tools=tools,
        instructions=[
            VERIFICATION_INSTRUCTION,
            "Mine customer reviews, feedback, and sentiment from relevant platforms for ANY business type.",
            "",
            "GOOGLE MAPS SCRAPER INSTRUCTIONS:",
            "- **PRIMARY TOOL:** Use the 'scrape' tool with query set to each competitor's exact business name (from the competitor list) and location='{location}' to get Google Maps review data",
            "- The scraper provides: exact review counts, ratings, and can extract up to ~300 reviews with --extra-reviews flag",
            "- Use scraper data as the single source of truth for review counts and ratings",
            "- **CRITICAL FALLBACK:** If scraper fails, returns error, or times out, IMMEDIATELY use search tools with that competitor's name plus 'Google Maps rating review count'",
            "- Extract rating and review count from search snippet using regex patterns like 'X.X/5 (N reviews)' or 'X.X stars N reviews'",
            "- The scraper returns JSON with review data - extract and format into your analysis",
            "",
            "VERIFICATION RULES:",
            "- **Verified Quotes Only:** Only include customer quotes that you can verify appear on a real review platform (Google, Yelp, TripAdvisor, Facebook).",
            "- **Quote Source Restriction:** ONLY include quotes from Google Reviews, Yelp, TripAdvisor, or Facebook Reviews. REJECT quotes from travel blogs, magazines, or news articles.",
            "- **Quote Attribution:** Each quote must include platform name and date in YYYY-MM-DD format.",
            "- **Exact Wording:** Use exact wording from review. Do not paraphrase or modify quotes.",
            "- **No Invented Quotes:** If you cannot find a specific quote for a theme, do not invent one. Use general descriptions instead.",
            "- **No 'Derived from review analysis' quotes:** NEVER use phrases like 'Derived from review analysis' or similar. Either provide actual verified quotes with platform/date, or remove the quote entirely.",
            "- **Quote Verification:** Each quote must be attributable to a specific review or source. If you cannot verify the exact quote, use a general description instead.",
            "- **Sentiment Trend Over Time:** Analyze if sentiment is improving, declining, or stable by looking at recent vs. older reviews.",
            "- **Theme Clustering:** Group reviews into themes (e.g., Service, Product Quality, Value, Environment) and calculate percentage of reviews mentioning each theme.",
            "",
            "STRICT QUOTE SOURCE RULES:",
            "- If you find a quote from Condé Nast Traveler or any blog, skip it. Only use customer review platforms.",
            "- Reject quotes from travel blogs, magazines, news articles, or any non-review source.",
            "- Each quote must be from an allowed review platform: Google Reviews, Yelp, TripAdvisor, Facebook Reviews.",
            "- If a quote cannot be verified to come from an allowed review platform, do not include it.",
            "",
            "SINGLE SOURCE OF TRUTH FOR REVIEW COUNTS:",
            "- **Google Maps Scraper is the primary source** for all review counts",
            "- Use the 'scrape' tool first to get Google Maps review data",
            "- If scraper unavailable, fetch Google review count via search and use it as the single source of truth",
            "- If Google Maps data unavailable, use the most recent verified source and explicitly state the source",
            "- **Never report conflicting numbers** - if Yelp shows 587 and Google shows 3500, use Google (3500) and note the discrepancy",
            "- Document the source for every review count: 'Google Maps: 3500 reviews (verified via scraper)'",
            "- All other agents must use the same Google Maps review count for consistency",
            "",
            "ANTI-REPETITION RULES:",
            "- DO NOT repeat the same customer feedback multiple times",
            "- DO NOT duplicate review analysis sections",
            "- Each competitor should be analyzed ONCE with complete feedback data",
            "- DO NOT repeat company name excessively in feedback sections",
            "- Keep feedback analysis structured and non-redundant",
            "- Use tables and bullet points for clear presentation",
            "",
            "COMPLETION RULES:",
            COMPLETION_RULE_INSTRUCTION,
            "- Ensure all customer feedback analysis is complete before finishing each competitor section",
            DOMAIN_ADAPTATION_INSTRUCTION,
            "- Perform comprehensive customer feedback analysis for {company} and competitors in {domain} in {location}. Adapt your analysis to the specific business type ({domain}).",
            COMPETITOR_ANALYSIS_INSTRUCTION,
            "",
            "UNIVERSAL BUSINESS FEEDBACK SOURCES:",
            "- **Products:** Product reviews, e-commerce ratings, customer testimonials",
            "- **Services:** Service reviews, client testimonials, professional ratings",
            "- **Digital:** App store reviews, software ratings, user feedback",
            "- **Professional:** Client reviews, peer recommendations, industry ratings",
            "- **Industrial:** B2B reviews, client testimonials, quality certifications",
            "- **Entertainment:** Event reviews, venue ratings, audience feedback",
            "- **Real Estate:** Property reviews, tenant feedback, client testimonials",
            "- **Healthcare:** Patient reviews, medical ratings, wellness feedback",
            "",
            "In example search strings below, «COMP» means substitute that competitor's exact business name.",
            "PRIMARY LOCAL REVIEW SOURCES TO MINE:",
            "  1. Google Reviews — search '«COMP» Google reviews {location}' → extract ratings and quotes",
            "  2. Yelp — search '«COMP» Yelp reviews {location}' → Firecrawl the page",
            "  3. TripAdvisor — search '«COMP» TripAdvisor {location}' for tourism businesses",
            "  4. Facebook Reviews — search '«COMP» Facebook reviews {location}'",
            "  5. Local review sites — '«COMP» reviews {location}' (regional platforms)",
            "  7. Instagram — search '«COMP» {location} comments' for customer feedback",
            "  8. Local blogs — '«COMP» review {location} blog'",
            "",
            "SECONDARY SOURCES:",
            "  6. Reddit — search '«COMP» {location} reddit experience' (local subreddits)",
            "",
            "BUSINESS-SPECIFIC FEEDBACK TO ANALYZE:",
            "",
            "Adapt your analysis based on the business type ({domain}). Common feedback themes include:",
            "  - Product/Service quality and effectiveness",
            "  - Customer service and staff professionalism",
            "  - Value for money and pricing",
            "  - Environment/facilities (store, office, venue, etc.)",
            "  - Convenience and accessibility",
            "  - Communication and responsiveness",
            "",
            "COMPREHENSIVE CUSTOMER INTELLIGENCE PER COMPETITOR:",
            "",
            "### [Competitor] - Complete Customer Feedback Analysis",
            "**Overall Sentiment Score:** [Positive/Mixed/Negative] | **Sample Size:** [N reviews analyzed]",
            "",
            "**📊 Multi-Platform Rating Analysis:**",
            "| Platform | Rating | Review Count | Last Updated | Sentiment Trend |",
            "|----------|--------|-------------|--------------|---------------|",
            "| Google Maps | X.X/5 | N reviews | Date | Improving/Stable/Declining |",
            "| Yelp | X.X/5 | N reviews | Date | Trend analysis |",
            "| TripAdvisor | X.X/5 | N reviews | Date | Trend analysis |",
            "| Facebook | X.X/5 | N reviews | Date | Trend analysis |",
            "| Local Sites | X.X/5 | N reviews | Date | Trend analysis |",
            "",
            "**🎯 Detailed Sentiment Analysis:**",
            "- **Positive Sentiment:** [% of reviews] - [Main positive themes]",
            "- **Neutral Sentiment:** [% of reviews] - [Main neutral themes]",
            "- **Negative Sentiment:** [% of reviews] - [Main negative themes]",
            "- **Sentiment Trend Over Time:** [e.g., 'Positive: 70% (stable), Negative: 15% (down 2% from last quarter)']",
            "- **Trend Analysis:** [Explain if sentiment is improving, declining, or stable and why]",
            "",
            "**📊 Theme Clustering (Keyword-based Analysis):**",
            "- **Service:** [% of reviews mentioning service themes] - [Key service-related keywords found]",
            "- **Product/Service Quality:** [% of reviews mentioning quality themes] - [Key quality-related keywords found]",
            "- **Value/Pricing:** [% of reviews mentioning value themes] - [Key value-related keywords found]",
            "- **Environment/Facilities:** [% of reviews mentioning environment themes] - [Key environment-related keywords found]",
            "- **Location:** [% of reviews mentioning location themes] - [Key location-related keywords found]",
            "",
            "**⭐ Top Praise Categories (VERIFIED quotes):**",
            "**Product/Service Quality:** [X% of positive reviews]",
            "  - '[Exact customer quote about quality]' - [Platform, Date]",
            "  - '[Another specific positive quote]' - [Platform, Date]",
            "",
            "**Service Excellence:** [X% of positive reviews]",
            "  - '[Exact quote about staff/service]' - [Platform, Date]",
            "  - '[Another service-related quote]' - [Platform, Date]",
            "",
            "**Environment/Facilities:** [X% of positive reviews]",
            "  - '[Quote about environment/facilities]' - [Platform, Date]",
            "  - '[Another environment-related quote]' - [Platform, Date]",
            "",
            "**Value for Money:** [X% of positive reviews]",
            "  - '[Quote about reasonable prices]' - [Platform, Date]",
            "",
            "**🚨 Critical Issues (VERIFIED quotes):**",
            "**Service Problems:** [X% of negative reviews]",
            "  - '[Exact complaint about service]' - [Platform, Date]",
            "  - '[Another service issue quote]' - [Platform, Date]",
            "",
            "**Product/Service Quality Issues:** [X% of negative reviews]",
            "  - '[Exact complaint about quality]' - [Platform, Date]",
            "  - '[Another quality-related complaint]' - [Platform, Date]",
            "",
            "**Pricing Concerns:** [X% of negative reviews]",
            "  - '[Quote about high prices]' - [Platform, Date]",
            "  - '[Another pricing-related complaint]' - [Platform, Date]",
            "",
            "**Operational Issues:** [X% of negative reviews]",
            "  - '[Quote about wait times]' - [Platform, Date]",
            "  - '[Quote about capacity/crowding]' - [Platform, Date]",
            "  - '[Quote about parking/accessibility]' - [Platform, Date]",
            "",
            "**📈 Performance Metrics:**",
            "- **Average Rating Velocity:** [Change in rating over time]",
            "- **Review Frequency:** [Reviews per month]",
            "- **Customer Response Rate:** [% of reviews responded to]",
            "- **Issue Resolution Time:** [Average time to address complaints]",
            "- **Repeat Customer Mentions:** [% of reviews mentioning repeat visits]",
            "",
            "**🎪 Location-Specific Insights:**",
            "- **Peak Time Complaints:** [Specific busy period issues]",
            "- **Tourist vs Local Feedback:** [Different satisfaction patterns]",
            "- **Seasonal Variations:** [Summer/winter feedback differences]",
            "- **Accessibility Feedback:** [Parking/public transport/wheelchair access]",
            "",
            "**🏆 Competitive Advantages:**",
            "- [What customers consistently choose them for]",
            "- [Unique strengths mentioned in reviews]",
            "- [Loyalty drivers from customer feedback]",
            "",
            "**⚠️ Critical Vulnerabilities:**",
            "- [Main reasons customers leave negative reviews]",
            "- [Recurring complaints that could drive customers away]",
            "- [Service gaps that competitors exploit]",
            "",
            "**💡 Strategic Opportunities for {company}:**",
            "- [Specific gaps in competitor's customer experience]",
            "- [Unaddressed customer needs]",
            "- [Service improvement opportunities]",
            "",
            "**📋 Data Sources & Verification:**",
            "- [List of all review platforms and URLs analyzed]",
            "- [Dates of data extraction]",
        ],
        markdown=True,
    )
