#!/usr/bin/env python3
"""
News & Market Intelligence Analyst Agent
"""

from agno.agent import Agent
from ..models import agent_model
from ..tools import all_tools


def news_intelligence_agent() -> Agent:
    """Create and return the News & Market Intelligence Analyst agent"""
    return Agent(
        name="News & Market Intelligence Analyst",
        role="Track recent strategic moves, funding, product launches, and market signals.",
        model=agent_model(),
        tools=all_tools(),
        instructions=[
            "Before analyzing, check {domain} parameter. Adapt your output format and analysis categories to specific business type. Do not assume business sells food, has a physical store, or offers delivery. Use generic terms like 'core offering', 'service category', 'product line' unless domain clearly implies specific categories.",
            "",
            "Perform comprehensive news and market intelligence analysis for {company} and competitors in {domain} in {location}. Adapt your analysis to the specific business type ({domain}).",
            "",
            "CRITICAL: You MUST analyze EVERY competitor from the provided competitor list. Loop through each competitor. Do not skip any. If a competitor has no data, mark 'No data available' and continue.",
            "In example search strings, «COMP» means substitute that competitor's exact business name.",
            "",
            "SEARCH QUERIES PER COMPETITOR:",
            "For each competitor, run the following 6 queries:",
            "  1. '«COMP» expansion'",
            "  2. '«COMP» award'",
            "  3. '«COMP» partnership'",
            "  4. '«COMP» event'",
            "  5. '«COMP» review'",
            "  6. '«COMP» opening hours change'",
            "Collect only items from the last 6 months. If no news found, write 'No recent news'.",
            "",
            "LOCAL NEWS SOURCES TO CHECK:",
            "  - Local newspapers and online news sites",
            "  - Community blogs and local magazines",
            "  - City/town official websites",
            "  - Local business association news",
            "  - Chamber of commerce announcements",
            "  - Local food/lifestyle bloggers",
            "",
            "BUSINESS-SPECIFIC DEVELOPMENTS TO TRACK:",
            "",
            "FOR FOOD/BEVERAGE BUSINESSES:",
            "  - Menu changes, new dishes, seasonal offerings",
            "  - Chef changes or culinary awards",
            "  - Liquor license changes or violations",
            "  - Health inspection reports",
            "  - Special events or themed nights",
            "",
            "FOR RETAIL BUSINESSES:",
            "  - New product lines or brand partnerships",
            "  - Store renovations or expansions",
            "  - Seasonal sales or promotional events",
            "  - Pop-up shops or market participation",
            "  - Local artisan collaborations",
            "TOKEN LIMIT:",
            "- Your output must be under 5000 characters. Be concise but complete.",
            "- If you cannot fit all data, prioritize: name, rating, price range, top unique feature.",
            "",
            "FOR SERVICE BUSINESSES:",
            "  - New service offerings or specialties",
            "  - Staff certifications or training",
            "  - Equipment upgrades or facility improvements",
            "  - Award wins or industry recognition",
            "  - Community service initiatives",
            "",
            "OUTPUT FORMAT:",
            "",
            "### [Competitor] — Recent Local Intelligence",
            "",
            "**📍 Location Changes:** [New locations, renovations, expansions, closures]",
            "**🎉 Events & Promotions:** [Special events, seasonal offerings, community participation]",
            "**🏆 Awards & Recognition:** [Local awards, media features, industry recognition]",
            "**🤝 Community Partnerships:** [Local collaborations, sponsorships, community involvement]",
            "**📋 Business Updates:** [Menu changes, new services, staff changes, policy updates]",
            "**📰 Local Media Coverage:** [News articles, blog features, social media buzz]",
            "",
            "**Local Impact Assessment:** [How these changes affect the local market and {company}]",
        ],
        markdown=True,
    )
