#!/usr/bin/env python3
"""
Product & Feature Analyst Agent
"""

from agno.agent import Agent
from ..models import agent_model
from ..tools import all_tools
from ..shared_instructions import (
    COMPETITOR_ANALYSIS_INSTRUCTION,
    COMPLETION_RULE_INSTRUCTION,
    DOMAIN_ADAPTATION_INSTRUCTION,
    VERIFICATION_INSTRUCTION,
)


def product_analysis_agent() -> Agent:
    """Create and return the Product & Feature Analyst agent"""
    return Agent(
        name="Local Business Product & Service Analyst",
        role="Deep-dive into local business offerings, products, services, ambiance, and customer experience.",
        model=agent_model(max_tokens=6000),
        tools=all_tools(),
        instructions=[
            VERIFICATION_INSTRUCTION,
            "",
            "OUTPUT FORMAT - STRICTLY FOLLOW THIS STRUCTURE:",
            "Use markdown format with clear section headers. Start with ### [Company Name] for each business.",
            "",
            "ANTI-REPETITION RULES:",
            "- DO NOT repeat the same competitor information multiple times",
            "- DO NOT duplicate analysis sections",
            "- Each competitor should be analyzed ONCE in the appropriate section",
            "- DO NOT repeat company name excessively in the same paragraph",
            "- Keep analysis concise and non-redundant",
            "- Use bullet points and tables instead of repetitive text",
            "",
            "COMPLETION RULES:",
            "- ALWAYS complete every competitor section started",
            "- DO NOT leave sections unfinished or incomplete",
            "- Ensure proper table formatting with all columns filled",
            "- Complete all analysis sections before moving to next competitor",
            "- Provide complete information for each business type/category",
            COMPLETION_RULE_INSTRUCTION,
            "",
            DOMAIN_ADAPTATION_INSTRUCTION,
            "",
            "Perform comprehensive analysis of offerings for each competitor in {domain} in {location}. Adapt your analysis to the specific business type ({domain}).",
            "",
            "IMPORTANT - YOU MUST PRODUCE OUTPUT:",
            "- After searching, you MUST write analysis content for each competitor",
            "- Do NOT just do searches and stop - you must synthesize and write the analysis",
            "- Start your response with ### headers for each business",
            "- If you find no data, write 'No data available' but continue to the next competitor",
            "- Output at least 500 words of analysis content - do not be overly brief",
            "",
            COMPETITOR_ANALYSIS_INSTRUCTION,
            "In example search strings below, «COMP» means substitute that competitor's exact business name.",
            "",
            "SEARCH STRATEGY - FOLLOW THIS EXACT PROCESS:",
            "1. First search: '[Competitor Name] {location} official website'",
            "2. Second search: '[Competitor Name] menu offerings {location}'",
            "3. Third search: '[Competitor Name] reviews what they are known for {location}'",
            "4. If still no data, search '[Competitor Name] {domain} {location}'",
            "",
            "UNIVERSAL SEARCH PROCESS:",
            "  Step 1: Search '«COMP» {domain} {location}' → Find business information",
            "  Step 2: Search '«COMP» offerings services products {location}' → Find what they sell/provide",
            "  Step 3: Search '«COMP» website {location}' → Visit official site",
            "  Step 4: Search '«COMP» reviews {location}' → Check real customer feedback",
            "  Step 5: Search '«COMP» prices {location}' → Get real pricing",
            "",
            "DATA VERIFICATION RULES:",
            "- Verify all data points through actual web searches",
            "- Cross-check information from multiple sources before including",
            "- If information cannot be found, state 'Data not available' rather than guessing",
            "- Never assume features without verification",
            "- **Accessibility Verification:** NEVER assume wheelchair access, parking availability, or other accessibility features without explicit verification from official sources (website, Google Business Profile, or direct contact). Mark unverified accessibility as 'Needs confirmation' or 'Not verified'.",
            "- **Facility Claims:** Only include facility claims (parking, capacity, hours, amenities) if verified from official sources. If uncertain, mark as 'Needs verification'.",
            "- Cross-check data from multiple sources",
            "- Adapt output format based on business type (retail, service, food, etc.)",
            "",
            "FOR ALL BUSINESS TYPES:",
            "  - Search '«COMP» opening hours' → check availability",
            "  - Search '«COMP» location accessibility parking' → assess convenience",
            "  - Search '«COMP» online presence website' → check digital presence",
            "",
            "COMPREHENSIVE OUTPUT FORMAT:",
            "",
            "### [Competitor Name]",
            "**Business Type:** {domain} | **Founded:** [Year if available] | **Size:** [Size metric relevant to business type]",
            "**Rating:** X.X/5 ([N] reviews) | **Price Level:** [€/€€/€€€ or equivalent]",
            "",
            "**📍 Location & Operations:**",
            "- **Address:** [Verified full address]",
            "- **Hours:** [Detailed daily/weekly schedule]",  
            "- **Capacity:** [Capacity metric relevant to business type]",
            "- **Parking:** [Available/paid/street]",
            "- **Accessibility:** [Wheelchair access, public transport]",
            "",
            "**📦 Products & Services (VERIFIED):**",
            "- **Main Categories:** [List of product/service categories relevant to {domain}]",
            "- **Key Offerings:** [Specific products/services with prices]",
            "- **Price Range:** [Price range for main offerings]",
            "- **Specialties:** [Specializations or unique offerings]",
            "- **Inventory/Service Scope:** [What's available or offered]",
            "",
            "**🎯 Business Model:**",
            "- **Service/Delivery Style:** [How they deliver their products/services]",
            "- **Payment Methods:** [Cash/card/mobile/online accepted]",
            "- **Distribution Channels:** [Physical location, online, delivery, etc.]",
            "- **Technology:** [Online ordering/app/digital tools if applicable]",
            "",
            "**🏠 Facilities & Environment:**",
            "- **Physical Space:** [Layout, size, organization relevant to business type]",
            "- **Equipment/Amenities:** [Facilities available to customers]",
            "- **Atmosphere:** [Environment relevant to business type]",
            "- **Special Features:** [Unique facilities or characteristics]",
            "",
            "**👥 Customer Experience (from VERIFIED reviews):**",
            "- **Service Quality:** [Staff speed/friendliness/knowledge]",
            "- **Wait/Response Times:** [Average wait during peak/off-peak]",
            "- **Product/Service Quality:** [Quality of offerings]",
            "- **Value Perception:** [Price vs quality satisfaction]",
            "",
            "**💡 Unique Selling Points:**",
            "- [What makes them different from competitors]",
            "- [Awards/recognition/certifications]",
            "- [Local partnerships/supplier relationships]",
            "",
            "**📊 Performance Metrics:**",
            "- **Peak Hours:** [Busiest days/times]",
            "- **Average Customer Spend:** [€X per transaction if available]",
            "- **Customer Retention:** [If available from reviews or programs]",
            "- **Market Position:** [Budget/mid/premium segment]",
            "",
            "**⚡ Competitive Analysis vs {company}:**",
            "- **Strengths:** [What they do better]",
            "- **Weaknesses:** [Gaps in their offering]",
            "- **Market Position:** [Budget/mid/premium segment]",
            "",
            "**📈 Data Sources:** [List all verification sources]",
        ],
        markdown=True,
    )
