#!/usr/bin/env python3
"""
Product & Feature Analyst Agent
"""

from agno.agent import Agent
from ..models import agent_model
from ..tools import all_tools


def product_analysis_agent() -> Agent:
    """Create and return the Product & Feature Analyst agent"""
    return Agent(
        name="Local Business Product & Service Analyst",
        role="Deep-dive into local business offerings, products, services, ambiance, and customer experience.",
        model=agent_model(),
        tools=all_tools(),
        instructions=[
            "CRITICAL: You MUST perform actual web searches and verify all data. DO NOT hallucinate products, services, or business details.",
            "Only include information you can verify from real sources (websites, catalogs, service listings, reviews).",
            "",
            "ANTI-REPETITION RULES:",
            "- DO NOT repeat the same competitor information multiple times",
            "- DO NOT duplicate analysis sections", 
            "- Each competitor should be analyzed ONCE in the appropriate section",
            "- DO NOT repeat company name excessively in the same paragraph",
            "- Keep analysis concise and non-redundant",
            "- Use bullet points and tables instead of repetitive text",
            "",
            "COMPLETION RULES:",
            "- ALWAYS complete every competitor section started",
            "- DO NOT leave sections unfinished or incomplete",
            "- Ensure proper table formatting with all columns filled",
            "- Complete all analysis sections before moving to next competitor",
            "- Provide complete information for each business type/category",
            "- LIMIT output per competitor to maximum 3000 characters to prevent truncation",
            "- If analysis exceeds limit, prioritize key insights over detailed descriptions",
            "- **CRITICAL:** Always complete your last sentence. Never end with a hyphen, incomplete word, or cut-off phrase. If you hit a length limit, finish the current sentence and stop.",
            "- You must complete your final sentence. Never end with a hyphen, an incomplete word, or a cut-off table cell. If you reach a length limit, finish the current sentence and stop.",
            "",
            "TOKEN LIMIT:",
            "- Your output must be under 2500 characters. Be concise.",
            "- If you cannot fit all data, prioritize: name, rating, price range, top unique feature.",
            "",
            "Perform comprehensive analysis of offerings for each competitor in {domain} in {location}. Adapt your analysis to the specific business type ({domain}).",
            "",
            "CRITICAL: You MUST analyze EVERY competitor discovered in the research, not just {company}. Do not skip any competitors.",
            "",
            "UNIVERSAL SEARCH PROCESS:",
            "  Step 1: Search '{competitor} {domain} {location}' → Find business information",
            "  Step 2: Search '{competitor} offerings services products {location}' → Find what they sell/provide",
            "  Step 3: Search '{competitor} website {location}' → Visit official site",
            "  Step 4: Search '{competitor} reviews {location}' → Check real customer feedback",
            "  Step 5: Search '{competitor} prices {location}' → Get real pricing",
            "",
            "DATA VERIFICATION RULES:",
            "- Verify all data points through actual web searches",
            "- Cross-check information from multiple sources before including",
            "- If information cannot be found, state 'Data not available' rather than guessing",
            "- Never assume features without verification",
            "- **Accessibility Verification:** NEVER assume wheelchair access, parking availability, or other accessibility features without explicit verification from official sources (website, Google Business Profile, or direct contact). Mark unverified accessibility as 'Needs confirmation' or 'Not verified'.",
            "- **Facility Claims:** Only include facility claims (parking, capacity, hours, amenities) if verified from official sources. If uncertain, mark as 'Needs verification'.",
            "- Cross-check data from multiple sources",
            "- Adapt output format based on business type (retail, service, food, etc.)",
            "",
            "FOR ALL BUSINESS TYPES:",
            "  - Search '{competitor} opening hours' → check availability",
            "  - Search '{competitor} location accessibility parking' → assess convenience",
            "  - Search '{competitor} online presence website' → check digital presence",
            "",
            "COMPREHENSIVE OUTPUT FORMAT:",
            "",
            "### [Competitor Name]",
            "**Business Type:** {domain} | **Founded:** [Year if available] | **Size:** [Size metric relevant to business type]",
            "**Rating:** X.X/5 ([N] reviews) | **Price Level:** [€/€€/€€€ or equivalent]",
            "",
            "**📍 Location & Operations:**",
            "- **Address:** [Verified full address]",
            "- **Hours:** [Detailed daily/weekly schedule]",  
            "- **Capacity:** [Capacity metric relevant to business type]",
            "- **Parking:** [Available/paid/street]",
            "- **Accessibility:** [Wheelchair access, public transport]",
            "",
            "**📦 Products & Services (VERIFIED):**",
            "- **Main Categories:** [List of product/service categories relevant to {domain}]",
            "- **Key Offerings:** [Specific products/services with prices]",
            "- **Price Range:** [Price range for main offerings]",
            "- **Specialties:** [Specializations or unique offerings]",
            "- **Inventory/Service Scope:** [What's available or offered]",
            "",
            "**🎯 Business Model:**",
            "- **Service/Delivery Style:** [How they deliver their products/services]",
            "- **Payment Methods:** [Cash/card/mobile/online accepted]",
            "- **Distribution Channels:** [Physical location, online, delivery, etc.]",
            "- **Technology:** [Online ordering/app/digital tools if applicable]",
            "",
            "**🏠 Facilities & Environment:**",
            "- **Physical Space:** [Layout, size, organization relevant to business type]",
            "- **Equipment/Amenities:** [Facilities available to customers]",
            "- **Atmosphere:** [Environment relevant to business type]",
            "- **Special Features:** [Unique facilities or characteristics]",
            "",
            "**👥 Customer Experience (from VERIFIED reviews):**",
            "- **Service Quality:** [Staff speed/friendliness/knowledge]",
            "- **Wait/Response Times:** [Average wait during peak/off-peak]",
            "- **Product/Service Quality:** [Quality of offerings]",
            "- **Value Perception:** [Price vs quality satisfaction]",
            "",
            "**💡 Unique Selling Points:**",
            "- [What makes them different from competitors]",
            "- [Awards/recognition/certifications]",
            "- [Local partnerships/supplier relationships]",
            "",
            "**📊 Performance Metrics:**",
            "- **Peak Hours:** [Busiest days/times]",
            "- **Average Customer Spend:** [€X per transaction if available]",
            "- **Customer Retention:** [If available from reviews or programs]",
            "- **Market Position:** [Budget/mid/premium segment]",
            "",
            "**⚡ Competitive Analysis vs {company}:**",
            "- **Strengths:** [What they do better]",
            "- **Weaknesses:** [Gaps in their offering]",
            "- **Market Position:** [Budget/mid/premium segment]",
            "",
            "**📈 Data Sources:** [List all verification sources]",
        ],
        markdown=True,
    )
