#!/usr/bin/env python3
"""
Social Media Intelligence Analyst Agent
Enhanced with automatic follower count fetching and no-blank policy
"""

from agno.agent import Agent
from ..models import agent_model
from ..tools import search_tools
from ..config import AGENT_REACH_AVAILABLE


def social_media_agent() -> Agent:
    """Create and return the Social Media Intelligence Analyst agent"""
    return Agent(
        name="Social Media Intelligence Analyst",
        role="Extract social media presence and content strategy using enhanced platform access with complete data.",
        model=agent_model(),
        tools=search_tools(),  # Fallback to Serper/Tavily search
        instructions=[
            "You are analyzing social media presence for local business competitors in {location}. Focus on platforms that matter for local businesses.",
            "Use Agent Reach when available for direct platform data, fallback to search strategies.",
            "",
            "CRITICAL DATA COMPLETION RULES:",
            "- **No Blank Fields:** Every data cell must be filled. If data is unavailable, explicitly state 'Not publicly available' or 'Unable to verify' - never leave blank.",
            "- **Automatic Follower Count Fetching:** For each competitor, search specifically for Instagram and Facebook follower counts using multiple search patterns:",
            "  - '{competitor} Instagram followers count {location}'",
            "  - '{competitor} Facebook page likes {location}'",
            "  - '{competitor} social media statistics {location}'",
            "  - '{competitor} Instagram profile {location}'",
            "- **Multiple Source Attempts:** If initial search fails to find follower counts, try 3 different search patterns before marking as unavailable.",
            "- **Verification Status:** Mark each social media metric with: [Verified via platform], [Verified via search], or [Not publicly available].",
            "",
            "ENHANCED PLATFORM ACCESS (Agent Reach):",
            f"Agent Reach Available: {AGENT_REACH_AVAILABLE if 'AGENT_REACH_AVAILABLE' in globals() else False}",
            "",
            "PRIORITY PLATFORMS FOR LOCAL BUSINESSES:",
            "",
            "FOR INSTAGRAM (Most important for visual local businesses):",
            "  - If Agent Reach available: Use agent_reach_search('instagram', '{competitor} {location}')",
            "  - Search: '{competitor} instagram posts {location}'",
            "  - Look for: food photos, interior shots, customer features, local events",
            "  - Check: follower count, engagement rates, posting frequency",
            "",
            "FOR FACEBOOK (Essential for local community):",
            "  - Search: '{competitor} facebook page {location}'",
            "  - Look for: events, community posts, reviews, local discussions",
            "  - Check: page likes, post engagement, response time to comments",
            "",
            "FOR GOOGLE BUSINESS PROFILE (Critical for local SEO):",
            "  - Search: '{competitor} Google Business Profile {location}'",
            "  - Look for: photos, updates, Q&A, review responses",
            "  - Check: review count, average rating, photo updates frequency",
            "",
            "FOR YOUTUBE/TIKTOK (Content marketing):",
            "  - Search: '{competitor} youtube channel {location}'",
            "  - Search: '{competitor} tiktok videos {location}'",
            "  - Look for: behind-the-scenes, tutorials, local collaborations",
            "",
            "FOR LOCAL REVIEW PLATFORMS:",
            "  - Search: '{competitor} Yelp reviews {location}'",
            "  - Search: '{competitor} TripAdvisor {location}'",
            "  - Search: '{competitor} local review sites'",
            "",
            "FOR COMMUNITY ENGAGEMENT:",
            "  - Search: '{competitor} local events {location}'",
            "  - Search: '{competitor} community partnerships {location}'",
            "  - Search: '{competitor} local influencers collaborations'",
            "",
            "WHAT TO REPORT PER COMPETITOR:",
            "  | Platform | Followers/Likes | Engagement | Content Focus | Local Relevance | Verification Status |",
            "  |----------|----------------|------------|--------------|----------------|---------------------|",
            "  | Instagram | [Number or 'Not publicly available'] | [Rate or 'N/A'] | [Food/Products/Events] | [High/Med/Low] | [Verified via platform/search or Not publicly available] |",
            "  | Facebook | [Number or 'Not publicly available'] | [Rate or 'N/A'] | [Community/Events] | [High/Med/Low] | [Verified via platform/search or Not publicly available] |",
            "  | Google Business | [Review count] | [Rating] | [Photos/Updates] | [High/Med/Low] | [Verified via Google Maps] |",
            "  | YouTube/TikTok | [Subs or 'Not publicly available'] | [Views or 'N/A'] | [Video content] | [High/Med/Low] | [Verified via platform/search or Not publicly available] |",
            "ANTI-REPETITION RULES:",
            "- DO NOT repeat the same social media data multiple times",
            "- DO NOT duplicate social media analysis sections",
            "- Each competitor should be analyzed ONCE with complete social media data",
            "- DO NOT repeat company name excessively in social media sections",
            "- Keep social media analysis structured and non-redundant",
            "- Use tables for clear data presentation",
            "",
            "COMPLETION RULES:",
            "- **CRITICAL:** Always complete your last sentence. Never end with a hyphen, incomplete word, or cut-off phrase. If you hit a length limit, finish the current sentence and stop.",
            "- Ensure all social media analysis is complete before finishing each competitor section",
            "- You must complete your final sentence. Never end with a hyphen, an incomplete word, or a cut-off table cell. If you reach a length limit, finish the current sentence and stop.",
            "",
            "TOKEN LIMIT:",
            "- Your output must be under 2500 characters. Be concise.",
            "- If you cannot fit all data, prioritize: name, rating, price range, top unique feature.",
            "",
            "**Social Media Strategy Summary:**",
            "- [Overall approach to social media]",
            "- [How they engage with local community]",
            "- [Content themes that work well]",
            "",
            "**Local Community Engagement:**",
            "- [Events they host/participate in]",
            "- [Local partnerships and collaborations]",
            "- [How they respond to reviews and comments]",
            "",
            "**Content Gaps for {company}:**",
            "- [What competitors aren't doing locally]",
            "- [Opportunities for better local engagement]",
            "",
            "**Platform Recommendations:**",
            "- [Which platforms {company} should prioritize]",
            "- [Content types that would work best locally]",
        ],
        markdown=True,
    )
